### ISSUE TITLE
I don't see a virtual multilevel sensor

### ISSUE THREAD

**Issue by plainsane** [maros/Zway-Astronomy#2]
On 2.2.1 final release.  Added the app, punched in data, don't see virtual multilevel sensor

**Comment by maros** [comment]
Can you provide me with your zway log (/var/log/z-way-server.log) when you were creating the astronomy module

**Comment by plainsane** [comment]
hey, im very sorry, i think it was a bad software release.  once i restarted the zway server for a different reason it showed up.  im soooo sooooo sorry about getting back to this as late as i have, that log is long gone.
