### ISSUE TITLE
Module always creates Azimuth device

### ISSUE THREAD

**Issue by kvolden** [maros/Zway-Astronomy#5]
The module generates an Azimuth device regardless of whether the "Create azimuth device" checkbox is checked.

You probably want to check config.createAzimuthDevice somewhere around line 63 in index.js.

Running Z-Way 2.2.4 / UI version 1.5.0, but this was also the case on 2.2.3.

**Comment by maros** [comment]
Thank you for your bug report. The issue was fixed in version 1.09
