### ISSUE TITLE
Rounding of device level

### ISSUE THREAD

**Issue by kvolden** [maros/Zway-Astronomy#7]
Currently the device level is not rounded, and has a precision of 12 decimal places. The smarthome UI does the rounding of this value automatically, but other applications using the API might (and usually does) not. This produces some strange looking results in third party applications.

I suggest to do the rounding of device "level" values down to 1 decimal place in the Astronomy module itself, while of course keeping the high precision "altitude" and "azimuth" metrics.

**Comment by maros** [comment]
Was fixed in v1.10
